# Site settings
title: CartoDB Presentation
email: 
description: > # this means to ignore newlines until "baseurl:"
  CartoDB-20151215
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cartodb-20151215.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
